In [109]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import pickle
RANDOM_STATE = 7

In [4]:
df= pd.read_csv("data/final_dataset.csv")
df.head()

Diseases  itching  skin rash  nodal skin eruptions  \
0  Fungal infection        1          1                     1   
1  Fungal infection        0          1                     1   
2  Fungal infection        1          0                     1   
3  Fungal infection        1          1                     0   
4  Fungal infection        1          1                     1   

   dischromic  patches  continuous sneezing  shivering  chills  \
0                    1                    0          0       0   
1                    1                    0          0       0   
2                    1                    0          0       0   
3                    1                    0          0       0   
4                    0                    0          0       0   

   watering from eyes  stomach pain  ...  bladder discomfort  \
0                   0             0  ...                   0   
1                   0             0  ...                   0   
2                   0             0  ...                   0   
3                   0             0  ...                   0   
4                   0             0  ...                   0   

   foul smell of urine  continuous feel of urine  skin peeling  \
0                    0                         0             0   
1                    0                         0             0   
2                    0                         0             0   
3                    0                         0             0   
4                    0                         0             0   

   silver like dusting  small dents in nails  inflammatory nails  blister  \
0                    0                     0                   0        0   
1                    0                     0                   0        0   
2                    0                     0                   0        0   
3                    0                     0                   0        0   
4                    0                     0                   0        0   

   red sore around nose  yellow crust ooze  
0                     0                  0  
1                     0                  0  
2                     0                  0  
3                     0                  0  
4                     0                  0  

[5 rows x 132 columns]

In [80]:
symptoms_list = df.drop('Diseases', axis = 1).columns
disease_list = df['Diseases'].unique()

In [81]:
symptoms_list

Index(['itching', 'skin rash', 'nodal skin eruptions', 'dischromic  patches',
       'continuous sneezing', 'shivering', 'chills', 'watering from eyes',
       'stomach pain', 'acidity',
       ...
       'bladder discomfort', 'foul smell of urine', 'continuous feel of urine',
       'skin peeling', 'silver like dusting', 'small dents in nails',
       'inflammatory nails', 'blister', 'red sore around nose',
       'yellow crust ooze'],
      dtype='object', length=131)

In [82]:
disease_list

array(['Fungal infection', 'Allergy', 'GERD', 'Chronic cholestasis',
       'Drug Reaction', 'Peptic ulcer diseae', 'AIDS', 'Diabetes',
       'Gastroenteritis', 'Bronchial Asthma', 'Hypertension', 'Migraine',
       'Cervical spondylosis', 'Paralysis (brain hemorrhage)', 'Jaundice',
       'Malaria', 'Chicken pox', 'Dengue', 'Typhoid', 'hepatitis A',
       'Hepatitis B', 'Hepatitis C', 'Hepatitis D', 'Hepatitis E',
       'Alcoholic hepatitis', 'Tuberculosis', 'Common Cold', 'Pneumonia',
       'Dimorphic hemmorhoids(piles)', 'Heart attack', 'Varicose veins',
       'Hypothyroidism', 'Hyperthyroidism', 'Hypoglycemia',
       'Osteoarthristis', 'Arthritis',
       '(vertigo) Paroymsal  Positional Vertigo', 'Acne',
       'Urinary tract infection', 'Psoriasis', 'Impetigo'], dtype=object)

In [5]:
df.isnull().sum()

Diseases                0
itching                 0
skin rash               0
nodal skin eruptions    0
dischromic  patches     0
                       ..
small dents in nails    0
inflammatory nails      0
blister                 0
red sore around nose    0
yellow crust ooze       0
Length: 132, dtype: int64

In [24]:
from sklearn.model_selection import train_test_split
y= df['Diseases']
X = df.drop('Diseases', axis = 1).values
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2 , random_state = RANDOM_STATE)

In [25]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators = 100, random_state = RANDOM_STATE )
rf.fit(X_train, y_train)

RandomForestClassifier(random_state=7)

In [26]:
from sklearn.metrics import f1_score
print("Train f1_score:", f1_score(y_train, rf.predict(X_train), average = 'weighted'))
print("Test f1_score:", f1_score(y_test, rf.predict(X_test), average = 'weighted'))

Train f1_score: 1.0
Test f1_score: 1.0


In [33]:
X_train

array([[0, 1, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [1, 1, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 1, 1, 1],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [32]:
rf.predict([X_train[0]])

array(['Acne'], dtype=object)

In [99]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder

enc = OneHotEncoder()
one_hot = enc.fit_transform(df[['Diseases']])
y = one_hot.toarray()
X = df.drop('Diseases', axis = 1).values
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2 , random_state = RANDOM_STATE)

In [100]:
print(one_hot.toarray())

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [101]:
from xgboost import XGBClassifier

In [102]:
xgb = XGBClassifier(n_estimators = 100 , random_state = RANDOM_STATE)
xgb.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=100, n_jobs=None, num_parallel_tree=None,
              predictor=None, random_state=7, ...)

In [103]:
print("Train f1_score:", f1_score(y_train, xgb.predict(X_train), average = 'weighted'))
print("Test f1_score:", f1_score(y_test, xgb.predict(X_test), average = 'weighted'))

Train f1_score: 1.0
Test f1_score: 1.0


In [104]:
to_predict = X_train[0]
to_predict = np.expand_dims(to_predict, axis=0) 

In [105]:
predicted = xgb.predict([X_train[0]])

In [106]:
print(predicted)

[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [107]:
enc.inverse_transform(predicted)

array([['Acne']], dtype=object)

In [110]:
pickle.dump(xgb, open("xgb_classifier.pickle.dat", "wb"))
pickle.dump(enc, open("encoder.pickle.dat", "wb"))